_sass/design-system/_settings.scss
_sass/design-system/patterns/_form-selectors.scss

Radio Button Button-Group Alternate added padding and removed fixed
width.

Text Inputs and Form Selectors

---

_sass/design-system/_settings.scss
_sass/design-system/patterns/_form-selectors.scss

Edits made yesterday with Elizabeth to color values and form selector spacing.

Mh 07.27 cleanup

---

_config.yml
overview/index.html

Deleted overview directory and modified nav in _config.yml

Removed Overview Section

---

_sass/design-system/patterns/_tooltip.scss
assets/website/js/tooltip.js

This PR adds tooltip arrows to the SASS file and positioning logic to the JS.

Add tooltip positioning

---

Components/buttons.html
Components/form-inputs.html
Components/form-selectors.html
Components/tooltip.html
_sass/website/_component-page.scss

Copy/Paste color values to be changed with shared file cleanup.
This is a conflict rewrite to part of PR #19

Added Status Tag to Components

---

Components/buttons.html
Components/form-inputs.html
Components/form-selectors.html
Components/grid.html
Components/tooltip.html
_data/colors.yml
_layouts/website/categories.html
_sass/design-system/_settings.scss
_sass/design-system/patterns/_form-selectors.scss
visuals/Iconography.html
visuals/colors.html
visuals/typography.html

trying to make some changes to the overview page… grid not working. help?

Eag content updates

---

Components/buttons.html
Components/form-inputs.html
Components/form-selectors.html
Components/grid.html
Components/tooltip.html
_sass/design-system/patterns/_buttons.scss
_sass/design-system/patterns/_form-inputs.scss
_sass/design-system/patterns/_tooltip.scss
_sass/website/_buttons.scss
_sass/website/_component-page.scss
assets/website/js/tooltip.js
css/website.scss
visuals/colors.html
visuals/typography.html

Reverts rackerlabs/design-system#36

Revert "Eag refinement"

---

Components/buttons.html
_includes/website/head.html
_sass/design-system/patterns/_buttons.scss
_sass/design-system/patterns/_form-selectors.scss
assets/website/js/elements.js
css/jquery-ui.css

Reverts rackerlabs/design-system#39

Revert "Revert "Mh dropdown button""

---

Components/buttons.html
Components/form-selectors.html
visuals/Iconography.html

Proof Reading Changes

---

_includes/website/header.html

This adds the baseurl to the header logo.

feat(header): adds baseurl to src in header logo

---

resources/index.html

Removed promised date.

---

Components/form-inputs.html
Components/form-selectors.html
_sass/design-system/patterns/_buttons.scss
_sass/design-system/patterns/_form-selectors.scss
assets/js/elements.js
css/jquery-ui.css
resources/index.html

Dropdown Menu Style Updates
Simple Selector States
Typeahead

Selectors check radio

---

_includes/website/head.html
_layouts/website/default.html

js refactoring in advance of date and time pickers. comments where additional component scripts will be eliminated.

Reorg external files

---

index.html
upcoming/index.html

Quick fix to add missing container.

Upcoming missing to-do bar container

---

components/charts.html

Charts page is behind on global style changes

Formatting fix to inherit new page dividers

---

_layouts/website/default.html
_sass/helix/_settings.scss
_sass/helix/components/_cards.scss
_sass/helix/components/_charts.scss
assets/js/demo-charts.js
components/charts.html
css/helix.scss

Chart specific changes split off from EAG Progress Bars branch.

EAG: Charts - Doughnuts, Statistics, Impressions

---

Components/progress-indicators.html

Hiding until ready for live site so we can push charts edits to production.

Hiding progress indicators WIP

---

_sass/website/_layout.scss
components/form-selectors.html

Adding links to facilitate work session

Add section anchors to selectors

---

_sass/helix/_icon.scss

One more attempt to correct issues on staging, runs locally.

Font linking - staging

---

_sass/helix/components/_form-inputs.scss
_sass/helix/components/_tooltip.scss

Minor corrections before updating master.

Input corrections

---

_sass/helix/semantic-ui-overrides/collections/_form.scss
_sass/helix/semantic-ui-overrides/collections/_message.scss
_sass/helix/semantic-ui-overrides/elements/_input.scss

Validation and subtext revisions

Text inputs

---

_sass/helix/semantic-ui-overrides/elements/_button.scss

Selector button group states 10.31

---

_config.yml

added the CDN URL to config -- merging to master to check CICD still works

feat(cdn): adds CDN URL to config

---

components/bucket-selector.html
components/cards.html
components/content-dividers.html
components/labels-chips.html
components/notifications.html
components/search.html
components/status-indicators.html
components/stepper.html
components/tabs.html
components/tags.html

Queuing up pages for group editing

Content additions

---

components/notifications.html
style/typography.html

Fixes sizing on SVGs in the Notifications section.
Fixes typo on the Typography page for H1 light.

Fix alert image sizes

---

components/bucket-selector.html

Palindromebart patch 3

---

_includes/website/header.html
resources/index.html

Added workflow diagrams for Helix contribution.

Added Contribute page

---

contribute/index.html

Reordered images

---

components/search.html

-Fixed a typo
-Moved images to Helix CDN
-Changed all but 1 image to SVG
-Updated Date Selector state to use new Date/Time Selector visuals

Fixed a typo; Updated images

---

.travis.yml
_prod-config.yml
_staging-config.yml

testing travis script with dynamic config

Add staging config

---

_sass/website/_layout.scss
resources/index.html
style/iconography.html

Updated links for Ds font and sketch resources. Small grid improvements on icon page.

Sprint2 updates

---

components/date-time-pickers.html

Bug fix for the SVG displaying date range selection.

Sprint4 updates

---

_config.yml
_includes/website/footer.html
_sass/website/_layout.scss
assets/js/navigation.js
layout/architecture.html
layout/global-layer.html
templates/email-template.html
templates/index.html

First pass at the Application Layers and Global Layers pages. Also begin work on a dynamic ul for h2 content for in page navigation. @araiford Gonna need some assistance on this feature (see commit 5b9e783)

Feature layout/evan

---

components/tables.html

Added examples for each sort order:
- Alphabetic
- Numeric
- Temporal

Add Sort Order Examples

---

_docs/layout/page-layouts.md

Docs edits for page-layouts

---

_docs/layout/navigation.md

SURF-549 Doc edits for app nav

---

_component_design/breadcrumbs.md

Edit to breadcrumbs

---

contribute.md

Make the example path to local images more explicit.

Fix example image path

---

templates/_includes/nav.html

in relation to https://github.com/rackerlabs/helix-ui/pull/44

surf-566-update-nav-hx-reveal

---

_data/navigation.csv
templates/_includes/nav.html

Found a missing closing bracket; it was messing with the staging build on FF55. Also fixed the Arch&Layout issue as the new nav got crowded.

caught typo while building staging

---

_component_design/tabs.md
assets/images/components/content-areas/tabs/tabs-content-area.svg
assets/images/components/content-areas/tabs/tabs-hover-state.svg
assets/images/components/content-areas/tabs/tabs-lorem-ipsum.svg
assets/images/components/content-areas/tabs/tabs-menu.svg
assets/images/components/content-areas/tabs/tabs-pressed-state.svg
assets/images/components/content-areas/tabs/tabs-zero-state.svg

Includes my edits on content from PDF
Needs:
- new image files and links
- additional markup
- content review

SURF-308 Edited content for tabs

---

templates/_includes/head-polyfills.html
templates/_includes/head-styles.html
templates/_includes/nav.html
templates/_includes/overview-footer.html
templates/base.html
templates/base2.html
templates/code.html
templates/docs.html
templates/overview.html

* Simplify markup
* Correct classes based on update to toolkit
-----
```html
<html>
<head>...</head>
<body class="hxApp">
<header class="hxApp__header">...</header>
<div class="hxApp__container">
<main class="hxApp__content">...</main>
<nav class="hxApp__nav">...</nav>
</div>
<footer class="hxApp__footer">...</footer>
</body>
</html>
```

refactor(markup): fix and refactor for simplification

---

_docs/layout/architecture.md
_docs/layout/global-layer.md
assets/css/_sass/website/_layout.scss
templates/_includes/nav.html

Fixes [SURF-588](https://jira.rax.io/browse/SURF-588), [SURF-590](https://jira.rax.io/browse/SURF-590), and [SURF-591](https://jira.rax.io/browse/SURF-591)

Left nav cleanup

---

_component_design/content-areas.md
_component_design/data-visualizations.md
_component_design/editing.md
_component_design/help.md
_component_design/inputs-and-controls.md
_component_design/navigation.md
_component_design/notifications.md
_component_design/processing.md
_component_design/search-and-filters.md
_component_design/selectors.md
_component_design/tables.md
assets/css/_sass/website/_component-page.scss
assets/css/_sass/website/_docs-page.scss
assets/css/_sass/website/_family-page.scss
assets/css/_sass/website/_layout.scss
templates/_includes/component-row.html
templates/base.html
templates/component.html
templates/docs.html
templates/family.html

**Significant changes:**
- Adds a content-wrapper class which facilitates max-width and horizontal centering for content on the helix site.
- Creates a new component-row.html which gets included in each family page, rather than having duplicate raw html on each one.
**Minor changes:**
- Adjusts the component detail header so that the breadcrumbs and buttons are on the same horizontal line.

Fix family pages

---

index.md
templates/base.html

Jira: https://jira.rax.io/browse/SURF-503

refactor(button): updated buttons to reflect updated helix ui css

---

assets/css/_sass/website/_docs-page.scss
assets/css/_sass/website/_family-page.scss
templates/_includes/component-row.html
templates/family.html

- Adds helix classes for headers
- moves component-row scss to family page where it belongs
- wraps the svgs on the component rows with a link to the component page

Family page tweaks

---

_component_design/application-navigation.md
_component_design/breadcrumbs.md
_component_design/footer.md
assets/css/_sass/website/_component-page.scss
templates/_includes/toc.html
templates/component.html

Made a few last tweaks to the footer article.

Fix formatting of footer website page surf 655

---

_config.yml
_plugins/helixKramdown.rb

adding new converter for Helix-based headings
Fixes SURF-693

[SURF-693] Automation of Helix Header Classes

---

_component_design/content-areas.md
_component_design/data-visualizations.md
_component_design/editing.md
_component_design/help.md
_component_design/inputs-and-controls.md
_component_design/navigation.md
_component_design/notifications.md
_component_design/processing.md
_component_design/search-and-filters.md
_component_design/selectors.md
_component_design/tables.md

Sorry, forgot to pull this out of my working branch and into a PR. Here's the fix to make the secondary metadata tag work.

Adding secondary metadata tag

---

_component_design/help-beacon.md
assets/images/components/help/beacon/beacon-hero.svg
assets/images/components/help/beacon/beacon-specs.svg

This PR moves the beacon documentation from sketch to md format. 
It is a fairly small doc. I am a little worried that the hero-image might be a bit hard to see. Perhaps we can have @etytaylor build a new hero image.

Website docs beacon evan

---

_component_design/actions-menu.md
assets/images/components/inputs-and-controls/actions-menu/actions-menu-advanced.svg
assets/images/components/inputs-and-controls/actions-menu/actions-menu-hero.svg
assets/images/components/inputs-and-controls/actions-menu/actions-menu-simple.svg

This PR converts the actions-menu.sketch file to HTML.
- New preview-image created and uploaded to the source file and CDN.
- Converted doc to HTML.
Should be ready to review.

Website docs actions menu evan

---

_component_design/help-link.md
_component_design/horizontal-stepper.md
_component_design/vertical-stepper.md

Hides the following pages that have not been surged: Help-link,
Horizontal-stepper, vertical-stepper

IA(hide-things): hiding unfinished patterns for relaunch

---

_data/families.csv

Removed as a single line commit for addition later, once data-viz has
been redesigned.

fix(data-vis): remove data visualization for now

---

_component_design/alert-bar.md
_component_design/badge.md
_component_design/key-value-pairs.md
_component_design/toast.md
_docs/getting-started/design.md

This PR fixes a few bugs that arose with the merges today. Also fixed the heading levels on a couple things Notes:
- Fixed Heading levels with Alert bars
- TOC fix badges
- TOC fix design getting started
- TOC fix K:V; Also segment document with divs
- TOC fix toasts

bug(docs): fixing couple md bugs across files

---

_docs/style/date-time.md

fix(date-time): markdown fix

---

_docs/getting-started/design.md
index.md

Fix the buttons on homepage
Fix the getting started markdown

Fix homepage buttons

---

templates/base.html
templates/base2.html
templates/overview.html

Adds missing favicon to the browser tab

Add Favicon

---

assets/css/_sass/website/_home.scss

[Bug] Fix hr

---

ISSUE_TEMPLATE.md
assets/css/_sass/website/_component-page.scss
templates/base.html

This creates the `ISSUE_TEMPLATE.md` file that was reviewed in the channel a couple week ago, sets up the button to create an issue in the following format: 
Issue Regarding - /components/$page
Also I hide the sketch template button and offset the issue button to take its place.

feature(issue-template): add issue template, link dynamic button

---

_component_design/choice-tiles.md
_docs/principles/accessibility.md

fix markdown and move H3 into proper location

bug(choice-tiles): fix markdown

---

assets/js/nav-accordion.js
templates/_includes/footer.html

basic, basic jQuery to hide nav sections accordion-like

Accordionize left nav

---

_component_design/actions-menu.md
_component_design/buttons.md
_component_design/modal.md
_component_design/popovers.md
_component_design/radio-buttons.md
_component_design/tooltip.md
assets/css/_sass/website/_layout.scss

Went through the site and tested all hyperlinks. Found a number of issues. Also the radio buttons page wasn't laying out correctly, fixed this. Finally added one line css change to side nav for anchor elements to have the same font-weight as hx-reveal items.
fixes #377 #375

Issues 375 377

---

_docs/getting-started/design.md

Pretty simple PR. 
-remove disabled attr
-Update link
I named the file v0.1. @araiford should we name this v1.0 or leave the v0.1 name

feat(sticker-sheet): update stickersheet link

---

_docs/principles/accessibility.md

closes #400 
Small wording nit.

Fix issue #400

---

index.md
templates/_includes/overview-footer.html

Fixing home links

---

_data/families.csv
assets/js/wayfinding.js
templates/_includes/footer.html
templates/_includes/nav.html
templates/base.html

Parent/Secondary Wayfinding

---

_component_design/alert-bar.md
_component_design/dropdowns.md
_component_design/footer.md
_component_design/popovers.md
_component_design/switches.md

Move alert- bar, dropdowns, switch, footer, popovers to stable status

docs(status): update docs status yaml

---

templates/_includes/search-box.html

Yes, I know how to fix things...

Fix search on staging

---

_component_design/actions-menu.md
_component_design/buttons.md
_component_design/cards.md
_component_design/loading-indicators.md
_component_design/vertical-stepper.md
_docs/layout/page-layouts.md
_docs/style/iconography.md

This PR pulls master into staging. Then we'll do a merge to master.
**Important**: This PR and the one to merge staging into master must use the standard merge strategy. Do **not** use "squash and merge" or "rebase and merge" as the merge strategy.

Prep staging for merge to master

---

_docs/getting-started/design.md
index.md

* update(docs): add low-fidelity stickersheet
* update(home-page): deep link to sketch resources
Allows users to move to getting-started page to self-select either the
full or low-fi stickersheet
* update(docs): language edits for high fidelity

update(docs): add low-fidelity sticker sheet (#483)

---

_docs/style/typography.md

Looks like these values were missed when I updated the heading names.

fix(headers): fix line-height && bottom-spacing values for headers

---

_docs/style/spacing.md

docs(typo): fix incorrect value

---

_docs/contact-us/index.md

uses CDN url for contact us avatars

refactor(markdown): switch site_url to cdn_url for avatars. (#555)

---

_data/helix-team.yml
_docs/contact-us/index.md

Adding new team member and small team logic

Adding Richard Goodwin

---

assets/images/preview-images/footer-thumbnail.svg

noticed the footer indicator in the thumbnail was incorrectly positioned.  fixed it.

refactor(images): updates footer thumbnail to correct layout

---

_docs/style/text-conventions/capitalization.md

update(body): changed instances of 'all-caps' to 'uppercase'
